[package]
name = "rust-playground"
version = "0.3.0"
authors = ["Jerzy Adamowski <jerzyadamowski@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
