[package]
name = "primitives-02"
version = "0.1.0"
authors = ["Jerzy Adamowski <jerzy.adamowski@ringieraxelspringer.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
